namespace Solstice.Members.BenefitModels
{
    public enum PlanTypeID
    {
        Unknown = 0,
        PPO_Medical = 9,
        POS_Medical = 10,
        HMO_Medical = 11,
        EPO_Medical = 12,
        PPO_Dental = 15,
        DHMO_Dental = 16,
        ScheduledReimbursement_Dental = 17,
        PPO_Vision = 18,
        Prepaid_Vision = 19,
        TermLife_Life = 20,
        VoluntaryLife_Life = 21,
        ShortTermDisability_Life = 22,
        LongTermDisability_Life = 23,
        HSA_HSA = 30,
        HRA_HRA = 31,
        FSA_FSA = 32,
        Indemnity_Dental = 34,
        Discount_Dental = 35,
        Discount_Vision = 36,
        Basic_Life = 37,
        Accident_Life = 38,
        ADandD_Life = 39,
        ChildSuplemental_Life = 40,
        SpouseSupplemental_Life = 41,
        CriticalIllness_Life = 42,
        Gap_Medical = 43,
        Supplemental_Life = 44,
        Wellness_Life = 45,
        WholeLife_Life = 46,
        Cancer_Life = 47,
        HospitalIndemnity_Life = 48,
        Dental_Life = 49,
        AflacCancer_Life = 50,
        Universal_Life = 51,
        EPO_Dental = 52,
        StopLoss_Medical = 53,
        Pharmacy_Medical = 54,
        Chiropractic_Medical = 55,
        Telemedicine_Medical = 56
    }
}
